stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/ms-text-gen"

build:
  stage: build
  image: node:20
  script:
    - npm install
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  image: docker:24
  services:
    - docker:dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
  tags:
    - docker
